apiVersion: v1
kind: Namespace
metadata:
  name: opal
---
apiVersion: v1
kind: Secret
metadata:
  name: opal-auth
  namespace: opal
type: Opaque
stringData:
  OPAL_AUTH_MASTER_TOKEN: THIS_IS_A_DEV_SECRET_CHANGE_ME
  OPAL_CLIENT_TOKEN: THIS_IS_A_DEV_SECRET_CHANGE_ME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: opal
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: opal
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: opal
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal-server
  namespace: opal
  labels:
    app: opal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opal-server
  template:
    metadata:
      labels:
        app: opal-server
    spec:
      containers:
      - name: opal-server
        image: permitio/opal-server:latest
        ports:
        - containerPort: 7002
          name: http
        env:
        - name: OPAL_POLICY_REPO_URL
          value: https://github.com/permitio/opal-example-policy-repo.git
        - name: OPAL_BROADCAST_URI
          value: postgres://postgres:postgres@postgres.opal.svc.cluster.local:5432/opal
        - name: OPAL_DATA_CONFIG_SOURCES
          value: >-
            {"config":{"entries":[{"url":"http://pep-proxy.proxy-system.svc.cluster.local:8080/opal/snapshots/tenant_policies","topics":["tenant_policies"],"dst_path":"/tenant_policies","save_method":"PUT"}]}}
        - name: OPAL_AUTH_MASTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: opal-auth
              key: OPAL_AUTH_MASTER_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: opal-server
  namespace: opal
spec:
  selector:
    app: opal-server
  ports:
  - name: http
    port: 7002
    targetPort: http
