apiVersion: v1
kind: Service
metadata:
  name: agentgateway-opa-sidecar
  namespace: agentgateway-system
spec:
  selector:
    app.kubernetes.io/name: agentgateway-proxy
    gateway.networking.k8s.io/gateway-name: agentgateway-proxy
  ports:
  - name: grpc
    port: 9191
    targetPort: 9191
    protocol: TCP
    appProtocol: kubernetes.io/h2c
  - name: http
    port: 8181
    targetPort: 8181
    protocol: TCP
